<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://empleado.parameta.com/"
           elementFormDefault="qualified"
           xmlns:tns="http://empleado.parameta.com/">

    <xs:element name="almacenarEmpleadoRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleado" type="tns:empleadoType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="almacenarEmpleadoResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="resultado" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="empleadoType">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="nombres" type="xs:string"/>
            <xs:element name="apellidos" type="xs:string"/>
            <xs:element name="tipoDocumento" type="xs:string"/>
            <xs:element name="numeroDocumento" type="xs:string"/>
            <xs:element name="fechaNacimiento" type="xs:string"/>
            <xs:element name="fechaVinculacion" type="xs:string"/>
            <xs:element name="cargo" type="xs:string"/>
            <xs:element name="salario" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>